apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: pgsql-service
spec:
  ports:
  - port: 80
    name: pgsql-service
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: LoadBalancer